/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    action: {
      codename: 'action',
      name: 'Akce',
      elements: {
        line1: {
          codename: 'line1',
          name: 'Řádek 1',
        },
        line2: {
          codename: 'line2',
          name: 'Řádek 2',
        },
        line3: {
          codename: 'line3',
          name: 'Řádek 3',
        },
        more_info_link: {
          codename: 'more_info_link',
          name: 'Odkaz pro více informací',
        },
      },
    },
    contact: {
      codename: 'contact',
      name: 'Kontakt',
      elements: {
        address___note: {
          codename: 'address___note',
          name: 'Adresa - poznámka',
        },
        zip_code: {
          codename: 'zip_code',
          name: 'PSČ',
        },
        map_link: {
          codename: 'map_link',
          name: 'Odkaz na mapy',
        },
        office_hours___note: {
          codename: 'office_hours___note',
          name: 'Úřední hodiny - poznámka',
        },
        city: {
          codename: 'city',
          name: 'Město',
        },
        phone: {
          codename: 'phone',
          name: 'Telefonní čísla',
        },
        map: {
          codename: 'map',
          name: 'Mapa',
        },
        e_mail: {
          codename: 'e_mail',
          name: 'E-mail',
        },
        street_number: {
          codename: 'street_number',
          name: 'Číslo domu',
        },
        street: {
          codename: 'street',
          name: 'Ulice',
        },
        office_hours: {
          codename: 'office_hours',
          name: 'Úřední hodiny',
        },
      },
    },
    date: {
      codename: 'date',
      name: 'Termín',
      elements: {
        free_places: {
          codename: 'free_places',
          name: 'Volné místa',
        },
        date: {
          codename: 'date',
          name: 'Datum',
        },
      },
    },
    form: {
      codename: 'form',
      name: 'Formulář',
      elements: {
        text: {
          codename: 'text',
          name: 'Text',
        },
        forms: {
          codename: 'forms',
          name: 'Formuláře',
        },
        drivers: {
          codename: 'drivers',
          name: 'Řidiči',
        },
      },
    },
    forms: {
      codename: 'forms',
      name: 'Formuláře',
      elements: {
        forms: {
          codename: 'forms',
          name: 'Formuláře',
        },
      },
    },
    gallery: {
      codename: 'gallery',
      name: 'Galerie',
      elements: {
        another_gallery_pictures: {
          codename: 'another_gallery_pictures',
          name: 'Obrázky',
        },
      },
    },
    homepage_photo: {
      codename: 'homepage_photo',
      name: 'Homepage foto',
      elements: {
        photo: {
          codename: 'photo',
          name: 'Fotka',
        },
      },
    },
    link: {
      codename: 'link',
      name: 'Odkaz',
      elements: {
        link: {
          codename: 'link',
          name: 'Odkaz',
        },
        url_slug: {
          codename: 'url_slug',
          name: 'Url',
        },
      },
    },
    news: {
      codename: 'news',
      name: 'Aktualita',
      elements: {
        text: {
          codename: 'text',
          name: 'Text',
        },
      },
    },
    phone_number: {
      codename: 'phone_number',
      name: 'Telefonní číslo',
      elements: {
        number: {
          codename: 'number',
          name: 'Číslo',
        },
      },
    },
    price: {
      codename: 'price',
      name: 'Cena',
      elements: {
        price: {
          codename: 'price',
          name: 'Cena',
        },
        note: {
          codename: 'note',
          name: 'Poznámka',
        },
      },
    },
    price_list: {
      codename: 'price_list',
      name: 'Ceník',
      elements: {
        price_for_downtime: {
          codename: 'price_for_downtime',
          name: 'Cena za prostoj',
        },
        tests_title: {
          codename: 'tests_title',
          name: 'Nadpis pro zkoušky',
        },
        workshops_title: {
          codename: 'workshops_title',
          name: 'Nadpis kurzů',
        },
        another_rides_title: {
          codename: 'another_rides_title',
          name: 'Nadpis pro další typy jízd',
        },
        tests: {
          codename: 'tests',
          name: 'Zkoušky',
        },
        workshop_type: {
          codename: 'workshop_type',
          name: 'Typ kurzů',
        },
      },
    },
    term: {
      codename: 'term',
      name: 'Termíny',
      elements: {
        heading: {
          codename: 'heading',
          name: 'Nadpis',
        },
        dates: {
          codename: 'dates',
          name: 'Termíny',
        },
        note: {
          codename: 'note',
          name: 'Bez termínů',
        },
      },
    },
    terms_page: {
      codename: 'terms_page',
      name: 'Termíny - stránka',
      elements: {
        terms: {
          codename: 'terms',
          name: 'Termíny',
        },
      },
    },
    test: {
      codename: 'test',
      name: 'Zkouška',
      elements: {
        name: {
          codename: 'name',
          name: 'Název',
        },
        whole_name: {
          codename: 'whole_name',
          name: 'Celý název',
        },
        note: {
          codename: 'note',
          name: 'Poznámka',
        },
        price: {
          codename: 'price',
          name: 'Cena',
        },
      },
    },
    text: {
      codename: 'text',
      name: 'Článek',
      elements: {
        text: {
          codename: 'text',
          name: 'Obsah',
        },
      },
    },
    vehicle: {
      codename: 'vehicle',
      name: 'Vozidlo',
      elements: {
        name: {
          codename: 'name',
          name: 'Název',
        },
        photo: {
          codename: 'photo',
          name: 'Fotka',
        },
        workshops: {
          codename: 'workshops',
          name: 'Skupiny/Kurzy',
        },
        price_for_90_minutes: {
          codename: 'price_for_90_minutes',
          name: 'Cena za 90 minut jízdy',
        },
        type: {
          codename: 'type',
          name: 'Typ vozidla',
        },
      },
    },
    workshop: {
      codename: 'workshop',
      name: 'Kurz',
      elements: {
        name: {
          codename: 'name',
          name: 'Název',
        },
        number_of_hours: {
          codename: 'number_of_hours',
          name: 'Počet hodin',
        },
        type: {
          codename: 'type',
          name: 'Typ',
        },
        price: {
          codename: 'price',
          name: 'Cena',
        },
      },
    },
  },
  taxonomies: {},
};
