import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Action = IContentItem<{
  line1: Elements.TextElement;
  line2: Elements.TextElement;
  line3: Elements.TextElement;
  more_info_link: Elements.RichTextElement;
}>;
