import { ContentItem, Elements } from "@kentico/kontent-delivery";

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Action extends ContentItem {
  public type: Elements.MultipleChoiceElement;
  public title: Elements.TextElement;
  public subtitle: Elements.TextElement;
  public note: Elements.TextElement;
  public moreInfoLink: Elements.RichTextElement;

  constructor() {
    super({
      propertyResolver: (elementName: string) => {
        if (elementName === "more_info_link") {
          return "moreInfoLink";
        }
        return elementName;
      },
    });
  }
}
