import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Contact = IContentItem<{
  address___note: Elements.TextElement;
  zip_code: Elements.TextElement;
  map_link: Elements.TextElement;
  office_hours___note: Elements.TextElement;
  city: Elements.TextElement;
  phone: Elements.RichTextElement;
  map: Elements.AssetsElement;
  e_mail: Elements.TextElement;
  street_number: Elements.NumberElement;
  street: Elements.TextElement;
  office_hours: Elements.TextElement;
}>;
