import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Form = IContentItem<{
  text: Elements.TextElement;
  forms: Elements.AssetsElement;
  drivers: Elements.MultipleChoiceElement;
}>;
