import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type PriceList = IContentItem<{
  price_for_downtime: Elements.NumberElement;
  tests_title: Elements.TextElement;
  workshops_title: Elements.TextElement;
  another_rides_title: Elements.TextElement;
  tests: Elements.RichTextElement;
  workshop_type: Elements.MultipleChoiceElement;
}>;
