import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Term = IContentItem<{
  heading: Elements.TextElement;
  dates: Elements.RichTextElement;
  note: Elements.TextElement;
}>;
