import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Test = IContentItem<{
  name: Elements.TextElement;
  whole_name: Elements.TextElement;
  note: Elements.TextElement;
  price: Elements.NumberElement;
}>;
