import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Workshop = IContentItem<{
  name: Elements.TextElement;
  number_of_hours: Elements.NumberElement;
  type: Elements.MultipleChoiceElement;
  price: Elements.RichTextElement;
}>;
